### ISSUE TITLE
Can the tutorial be more direct

### ISSUE THREAD

**Issue by wfwfwfw** [gliscowo/conjuring#13]
I'm Chinese. I can't understand the book in mod, but your introduction is very interesting. Hope your book can be more suitable for Xiaobai, let me use translation software to learn.
I don't know how to get c-junction essence。
When I perform the ceremony according to the result of the translation of the tutorial, I still can't run it.
![image](https://user-images.githubusercontent.com/72644389/123651288-ec1fd780-d85d-11eb-8b60-670f22c084bc.png)
![image](https://user-images.githubusercontent.com/72644389/123651346-f8a43000-d85d-11eb-9774-cfee4c1010ae.png)
![image](https://user-images.githubusercontent.com/72644389/123651643-3d2fcb80-d85e-11eb-8582-f8595ec2cc6d.png)

**Comment by Mosklia** [comment]
You need to trap a skeleton on the funnel.

By the way, I had submit a Chinese translation to the repo.

**Comment by gliscowo** [comment]
As the translation is on its way and the issue should be resolved when it gets merged, I will close this for now
